name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build Docker images
      uses: docker/bake-action@v4
      with:
        pull: true
        load: true
        files: |
          compose.yaml
        set: |
          *.cache-from=type=gha,scope=${{github.ref}}
          *.cache-from=type=gha,scope=refs/heads/main
          *.cache-to=type=gha,scope=${{github.ref}},mode=max
    -
      name: Start services
      run: docker compose up --wait --no-build
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm ci
    - run: lerna run tsc
    - run: npx playwright install --with-deps
    - run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright test --reporter json
    - uses: daun/playwright-report-summary@v3
      if: github.event_name == 'pull_request'
      with:
        report-file: results.json
        github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
