name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 'current'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: lerna run tsc
    - run: lerna publish --no-private
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
